FROM debian:stretch

WORKDIR /usr/share/kanboard

# Install nginx

RUN apt update
RUN apt install -y \
    nginx \
    git

# nginx Configuration
RUN rm /etc/nginx/sites-enabled/default
COPY ./configuration/nginx.conf /etc/nginx/sites-enabled/default

# Kanboard source code
RUN git clone https://github.com/kanboard/kanboard.git /usr/share/kanboard
RUN chown -R www-data:www-data /usr/share/kanboard

CMD [ "nginx" , "-g", "daemon off;" ]