FROM debian:stretch

WORKDIR /usr/share/kanboard

# Install nginx

RUN apt update
RUN apt install -y \
    nginx \
    git

# nginx Configuration
RUN rm /etc/nginx/sites-enabled/default
COPY ./configuration/nginx.conf /etc/nginx/sites-enabled/default

# Kanboard source code
RUN git clone https://github.com/kanboard/kanboard.git /usr/share/kanboard
RUN chown -R www-data:www-data /usr/share/kanboard

# Copy entrypoint
COPY scripts/entrypoint-web.sh /usr/share/entrypoint-web.sh

ENV FASTCGI_HOST=php-fpm
ENV FASTCGI_PORT=9100

CMD [ "/bin/bash", "/usr/share/entrypoint-web.sh" ]